name: nfc_wallet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_nfc_kit: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.2.3
  file_picker: ^8.0.5
  path_provider: ^2.1.3
  share_plus: ^9.0.0

flutter:
  uses-material-design: true
